name: My First CI Pipeline

# 1. The Trigger (Event)
on: [push]

jobs:
  # 2. The Job
  build-and-test:
    # 3. The Runner (GitHub-hosted Ubuntu machine)
    runs-on: ubuntu-latest

    # 4. The Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-devops-app:latest .

      - name: List Docker Images
        run: docker images
