name: My First CI Pipeline

# 1. The Trigger (Event)
on: [push]

jobs:
  # 2. The Job
  build-and-test:
    # 3. The Runner (GitHub-hosted Ubuntu machine)
    runs-on: ubuntu-latest

    # 4. The Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
      run: |
       docker build -t "${{ secrets.DOCKER_USERNAME }}/my-devops-app:latest" .
       docker push "${{ secrets.DOCKER_USERNAME }}/my-devops-app:latest"
